### PR TITLE
atom-material-ui's predefined colour setting now also affects cursors and line numbers

### PR DESCRIPTION
**Pull request by callodacity**
Pretty self-explanatory.

I thought this minor change complimented the theme changes when the user chooses a different colour.

### CODE REVIEW

**Comment by silvestreh** [comment]
This is something I've been wanting to do for a while, but I'm not comfortable with modifying other themes or messing with the syntax theme in the UI theme.

I still can't decide between scoping this only to `atom-material-syntax` themes or making it an optional feature in the settings. 😕

**Comment by callodacity** [comment]
I would definitely go with making in an optional feature (obsviously default value will be false). 

I'm probably just saying that because I created this PR and want this feature haha 😉

**Comment by silvestreh** [comment]
I'll merge this and implement the toggle 👍

**Comment by callodacity** [comment]
Legendary  👍

**Pull request merged**
