### PR TITLE
Add toggleable tab min- and max-width

### PR DESCRIPTION
**Pull request by supremebeing7**
This provides a toggleable solution to #229.

### CODE REVIEW

**Comment by supremebeing7** [comment]
I added specs for this as well, although the new specs as well as about 10 other specs (including all of the others in `settings-tabs-spec.js`) were failing for me locally, and I didn't have time to do a deep dive to find out what's going on. 

I assume, at least for those tests in `settings-tabs-spec.js`, that the failure is in the setup, so fixing one will fix them all.

**Comment by silvestreh** [comment]
Unfortunately, like I mentioned in another (unrelated) issue, I won't be able to check this out for a while as my computer is dead and I can't buy a new one. I'll sure try to check it out as soon as possible.

**Comment by supremebeing7** [comment]
No problem. Thanks for the heads up!

**Comment by silvestreh** [comment]
I'm not a fan of removing the `max-width` property from tabs. I can see the benefit of removing the `min-width` as it would remove the necessity for scrolling the tab bar. If you can update your PR I'll merge it. Thanks!

**Comment by supremebeing7** [comment]
Even though the `max-width` is toggleable and ***not*** removed by default?

I can definitely update the PR, though I'll just have to keep using my forked copy unfortunately because I have been really enjoying having no `max-width`.

**Comment by silvestreh** [comment]
👍  thanks!

**Comment by silvestreh** [comment]
@supremebeing7, I forgot to mention… run this command `git update-index --assume-unchanged styles/custom.less` to avoid changing the `custom.less` file in the future.

**Pull request merged**
